# Generated by Django 6.0 on 2025-12-26 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entexecutedcommand',
            name='deviceId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistant.entdevice'),
            preserve_default=False,
        ),
    ]
